### PR TITLE
Player.hat, unholy paragraphs, sound IDs

### PR DESCRIPTION
**Pull request by DecibillyJoel**
I hate luarocks

### CODE REVIEW

**Comment by DecibillyJoel** [comment]
Previews

image
image

**Comment by DecibillyJoel** [comment]
Bump @aromaa

**Comment by DecibillyJoel** [comment]
Bump @aromaa. Newest commit includes all the new features that have been added since, and deprecates player.chill() and player.dye(), and makes usage example blocks multiline.

**Comment by DecibillyJoel** [comment]
@aromaa When you build the LDoc, cd into the directory and run the command shown in ldoc_build_command.txt (you can change the -d flag to whatever)

**Comment by DecibillyJoel** [comment]
Added GitHub Actions workflow to create LDoc build artifact automatically upon push to repo. Additionally, you can trigger it manually in the Actions settings. I also left the Pages stuff in there as an optional parameter for manual trigger in case you decide you want to try it in the future.

**Comment by DecibillyJoel** [comment]
gone, reduced to atoms

**Comment by RMXdotEXE** [comment]
per request

**Pull request closed without merging**
